tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"

brew "clang-format"
brew "ctags"
brew "fzf"
brew "gcc"
brew "git"
brew "gnu-sed"
brew "go"
brew "grep"
brew "grpcurl"
brew "jq"
brew "lua"
brew "mas"
brew "nkf"
brew "plantuml"
brew "pyenv-virtualenv"
brew "reattach-to-user-namespace"
brew "telnet"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "zsh-completions"

cask "1password"
cask "alfred"
cask "appcleaner"
cask "blender"
cask "google-chrome"
cask "google-drive"
cask "google-japanese-ime"
cask "iterm2"
cask "kindle"
cask "micro-snitch"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "the-unarchiver"
cask "tradingview"

mas "BetterSnapTool", id: 417375580
mas "Bitdefender Virus Scanner", id: 500154009
mas "LINE", id: 539883307
mas "Todoist: To-Do List & Tasks", id: 585829637
mas "Xcode", id: 497799835
