tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "ktr0731/evans"
tap "shyiko/kubesec"

brew "arp-scan"
brew "clang-format"
brew "ctags"
brew "etcd"
brew "evans"
brew "ffmpeg"
brew "fzf"
brew "gcc"
brew "gdb", args: ["with-python"]
brew "git"
brew "gnu-sed"
brew "gnuplot"
brew "go"
brew "gpg"
brew "graphviz"
brew "grep", args: ["with-default-names"]
brew "grpcurl"
brew "hping"
brew "hugo"
brew "jq"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "kubesec"
brew "mas"
brew "nkf"
brew "nmap"
brew "openssl@1.1"
brew "pandoc"
brew "protobuf"
brew "pyenv-virtualenv"
brew "reattach-to-user-namespace"
brew "telnet"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"
brew "zsh-completions"

cask "1password6"
cask "adobe-creative-cloud"
cask "alfred"
cask "appcleaner"
cask "bettertouchtool"
cask "deckset"
cask "docker"
cask "dropbox"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-japanese-ime"
cask "intel-power-gadget"
cask "iterm2"
cask "karabiner-elements"
cask "kindle"
cask "mendeley"
cask "micro-snitch"
cask "minikube"
cask "onedrive"
cask "skim"
cask "spotify"
cask "station"
cask "sublime-text"
cask "the-unarchiver"
cask "transmission"
cask "vmware-fusion"
cask "vmware-remote-console"
cask "wireshark"

mas "Airmail 3", id: 918858936
mas "Bear", id: 1091189122
mas "Bitdefender Virus Scanner", id: 500154009
mas "LINE", id: 539883307
mas "MARKETSPEED", id: 946680495
mas "Xcode", id: 497799835
