#!/bin/bash

if [ "$1" = "-h" ]; then
    echo "Usage: $0 | brew bundle --file=-"
    exit 0
fi

read -d '' ignore_packages <<EOF
arp-scan
hping
hugo
minikube
nmap
appcleaner
deckset
karabiner-elements
kindle
micro-snitch
spotify
transmission
wireshark
Bear
Bitdefener
LINE
EOF

init=0
pattern=""
for package in ${ignore_packages}; do
    if [ ${init} -eq 0 ]; then
        pattern="${package}"
        init=1
    else
        pattern="${pattern}|${package}"
    fi
done

grep -v -E "${pattern}" Brewfile
